apiVersion: v1
kind: Service
metadata:
  name: piazza-dvs-service
  labels:
    app: piazza-dvs-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: piazza-dvs
  sessionAffinity: None